
import Db.DatabaseUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author AYMAN
 */
public class Livraison extends javax.swing.JFrame {

    private int livraisonPK = 0;

    /**
     * Creates new form Livraison
     */
    public Livraison() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private boolean validateFields() {

        if (!txtquan.getText().equals("") && !txtdate.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void getFournisseur() {

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT *FROM Fournisseurs";
            ResultSet rs = stmt.executeQuery(sql);
            combo2.removeAllItems();
            while (rs.next()) {
                combo2.addItem(rs.getString("FournisseurID") + "-" + rs.getString("SupplierName"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void getProduct() {

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT *FROM Product";
            ResultSet rs = stmt.executeQuery(sql);
            combo.removeAllItems();
            while (rs.next()) {
                combo.addItem(rs.getString("ProductID") + "-" + rs.getString("ArticleName"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        txtquan = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        livreTab = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Produit ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fournisseur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("quantité");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, -1, -1));

        combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        combo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, -1, -1));

        txtquan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, 212, -1));

        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 430, 212, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 392, -1, -1));

        livreTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "quantité", "Date", "Fournisseur id", "Fournisseur nom", "Produit Id", "Produit nom"
            }
        ));
        livreTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livreTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(livreTab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 162, 722, 222));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Ajouter");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 430, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("modifier");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 430, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("rester");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 430, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("fermer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Livraison management ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 6, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("chercher");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 88, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 120, 371, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/50-Beautiful-and-Minimalist-Presentation-Backgrounds-042.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        DefaultTableModel md = (DefaultTableModel) livreTab.getModel();
        md.setRowCount(0);

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT *FROM Livraisons  INNER JOIN Product ON  Livraisons.ProductID=Product.ProductID  INNER JOIN Fournisseurs  ON  Livraisons.FournisseurID =Fournisseurs.FournisseurID  ;";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                md.addRow(new Object[]{
                    rs.getInt("LivraisonID"),
                    rs.getInt("DeliveredQuantity"),
                    rs.getDate("DeliveryDate"),
                    rs.getInt("FournisseurID"),
                    rs.getString("SupplierName"),
                    rs.getInt("ProductID"),
                    rs.getString("ArticleName"),});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        btnUpdate.setEnabled(false);

        getProduct();
        getFournisseur();
    }//GEN-LAST:event_formComponentShown

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        new Livraison().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String four = (String) combo2.getSelectedItem();
        String fournID[] = four.split("-", 0);
        String prId = (String) combo.getSelectedItem();
        String proid[] = prId.split("-", 0);

        String quan = txtquan.getText();
        String dateStr = txtdate.getText();
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (validateFields()) {
            JOptionPane.showMessageDialog(null, "all field all requierd");
        } else {
            try {
                Date date = inputFormat.parse(dateStr);
                String formattedDate = outputFormat.format(date);
                Connection con = DatabaseUtil.getConnection();
                // Setting values for the placeholders
                PreparedStatement ps = con.prepareStatement("INSERT INTO Livraisons (DeliveredQuantity  ,DeliveryDate  ,FournisseurID,ProductID ) VALUES ( ?,?, ?, ?)");

                // Setting values for the placeholders
                ps.setString(1, quan);
                ps.setString(2, formattedDate);

                ps.setString(3, fournID[0]);
                ps.setString(4, proid[0]);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Livraison added successfully");
                new Livraison().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String quan = txtquan.getText();
        String dat = txtdate.getText();

        String four = (String) combo2.getSelectedItem();
        String fournID[] = four.split("-", 0);
        String po = (String) combo.getSelectedItem();
        String pID[] = po.split("-", 0);

        if (validateFields()) {
            JOptionPane.showMessageDialog(null, "all field all requierd");
        } else {
            try {
                Connection con = DatabaseUtil.getConnection();
                // Setting values for the placeholders
                PreparedStatement ps = con.prepareStatement("UPDATE Livraisons  set DeliveredQuantity =? , DeliveryDate =? ,FournisseurID=? ,ProductID=? where LivraisonID=?");

                // Setting values for the placeholders
                ps.setString(1, quan);
                ps.setString(2, dat);

                ps.setString(3, fournID[0]);
                ps.setString(4, pID[0]);

                ps.setInt(5, livraisonPK);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "livraison updated successfully");
                new Livraison().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void livreTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livreTabMouseClicked
        // TODO add your handling code here:

        int index = livreTab.getSelectedRow();
        TableModel model = livreTab.getModel();
        String id = model.getValueAt(index, 0).toString();
        livraisonPK = Integer.parseInt(id);

        String quan = model.getValueAt(index, 1).toString();
        txtquan.setText(quan);

        String date = model.getValueAt(index, 2).toString();
        txtdate.setText(date);

        combo2.removeAllItems();
        combo.removeAllItems();

        String fouID = model.getValueAt(index, 3).toString();
        String fouName = model.getValueAt(index, 4).toString();
        combo2.addItem(fouID + "-" + fouName);
        String pID = model.getValueAt(index, 5).toString();
        String pName = model.getValueAt(index, 6).toString();
        combo.addItem(pID + "-" + pName);
        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT * FROM Fournisseurs";
            String sqlu = "SELECT * FROM Product";

            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                combo2.addItem(rs.getInt("FournisseurID") + "-" + rs.getString("SupplierName"));
            }

            rs.close();  // Close the first result set before opening the second one

            ResultSet ru = stmt.executeQuery(sqlu);

            while (ru.next()) {
                combo.addItem(ru.getInt("ProductID") + "-" + ru.getString("ArticleName"));
            }

            ru.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_livreTabMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
           // TODO add your handling code here:
            int selectedRow = livreTab.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                // Get the FournisseurID from the selected row
                int fournisseurID = Integer.parseInt(livreTab.getValueAt(selectedRow, 0).toString());

                // Execute the DELETE SQL query
                Connection con = DatabaseUtil.getConnection();

                PreparedStatement ps = con.prepareStatement("DELETE FROM Livraisons  WHERE LivraisonID= ?");
                ps.setInt(1, fournisseurID);
                ps.executeUpdate();

                // Refresh the table data
                DefaultTableModel model = (DefaultTableModel) livreTab.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
             DefaultTableModel md = (DefaultTableModel) livreTab.getModel();
        md.setRowCount(0);

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM livraisons " +
             "INNER JOIN Product ON Livraisons.ProductID = Product.ProductID " +
             "INNER JOIN Fournisseurs ON Livraisons.FournisseurID = Fournisseurs.FournisseurID " +
             "WHERE Product.ProductID = " + txtSearch.getText();


            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                md.addRow(new Object[]{
                    
                rs.getInt("LivraisonID"),
                    rs.getInt("DeliveredQuantity"),
                    rs.getDate("DeliveryDate"),
                    rs.getInt("FournisseurID"),
                    rs.getString("SupplierName"),
                    rs.getInt("ProductID"),
                    rs.getString("ArticleName"),});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livraison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable livreTab;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtquan;
    // End of variables declaration//GEN-END:variables
}
