
import Db.DatabaseUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author AYMAN
 */
public class Societe extends javax.swing.JFrame {

    private int SocietePk = 0;

    /**
     * Creates new form Societe
     */
    public Societe() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private boolean validateFields() {

        if (!txtname.getText().equals("") && !txtRue.getText().equals("") && !txtVie.getText().equals("") && !txtadress.getText().equals("") && !txtTele.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void getFournisseur() {

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT *FROM Fournisseurs";
            ResultSet rs = stmt.executeQuery(sql);
            combo.removeAllItems();
            while (rs.next()) {
                combo.addItem(rs.getString("FournisseurID") + "-" + rs.getString("SupplierName"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtVie = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        txtRue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        socTab = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("société de distribution ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Téléphone ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 173, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Rue ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 255, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ville ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 337, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("adress");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 419, -1, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 129, 257, -1));

        txtTele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 211, 257, -1));

        txtVie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtVie, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 375, 255, -1));

        txtadress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 457, 255, -1));

        txtRue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtRue, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 293, 255, -1));

        socTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom ", "Telephone", "Rue", "Ville", "Adress", "Fournisseur id", "Fournisseur nom"
            }
        ));
        socTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(socTab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 161, 800, 278));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Ajouter ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 457, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Modifier");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 457, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 457, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Rester");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 457, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Fermer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 457, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 103, 379, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Chercher");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 71, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Fournisseur ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 502, -1, -1));

        combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 540, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/50-Beautiful-and-Minimalist-Presentation-Backgrounds-042.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        DefaultTableModel md = (DefaultTableModel) socTab.getModel();
        md.setRowCount(0);

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT *FROM DistributionCompany  INNER JOIN Fournisseurs ON  DistributionCompany.FournisseurID =Fournisseurs.FournisseurID;";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                md.addRow(new Object[]{
                    rs.getInt("DistributionCompanyID"),
                    rs.getString("CompanyName"),
                    rs.getString("CompanyPhone"),
                    rs.getString("CompanyStreet"),
                    rs.getString("CompanyCity"),
                    rs.getString("CompanyAddress"),
                    rs.getInt("FournisseurID"),
                    rs.getString("SupplierName")

                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        btnUpdate.setEnabled(false);

        getFournisseur();
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        new Societe().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            int selectedRow = socTab.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                // Get the FournisseurID from the selected row
                int fournisseurID = Integer.parseInt(socTab.getValueAt(selectedRow, 0).toString());

                // Execute the DELETE SQL query
                Connection con = DatabaseUtil.getConnection();

                PreparedStatement ps = con.prepareStatement("DELETE FROM DistributionCompany  WHERE DistributionCompanyID= ?");
                ps.setInt(1, fournisseurID);
                ps.executeUpdate();

                // Refresh the table data
                DefaultTableModel model = (DefaultTableModel) socTab.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String name = txtname.getText();
        String tele = txtTele.getText();
        String rue = txtRue.getText();
        String ville = txtVie.getText();
        String adress = txtadress.getText();

        String four = (String) combo.getSelectedItem();
        String fournID[] = four.split("-", 0);

        if (validateFields()) {
            JOptionPane.showMessageDialog(null, "all field all requierd");
        } else {
            try {
                Connection con = DatabaseUtil.getConnection();
                // Setting values for the placeholders
                PreparedStatement ps = con.prepareStatement("INSERT INTO DistributionCompany  (CompanyName , CompanyPhone , CompanyStreet,CompanyCity  ,CompanyAddress ,FournisseurID ) VALUES ( ?,?, ?, ?,?,?)");

                // Setting values for the placeholders
                ps.setString(1, name);
                ps.setString(2, tele);
                ps.setString(3, rue);
                ps.setString(4, ville);
                ps.setString(5, adress);

                ps.setString(6, fournID[0]);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Societe added successfully");
                new Societe().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void socTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socTabMouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:
        int index = socTab.getSelectedRow();
        TableModel model = socTab.getModel();
        String id = model.getValueAt(index, 0).toString();
        SocietePk = Integer.parseInt(id);

        String name = model.getValueAt(index, 1).toString();
        txtname.setText(name);

        String tel = model.getValueAt(index, 2).toString();
        txtTele.setText(tel);

        String rue = model.getValueAt(index, 3).toString();
        txtRue.setText(rue);

        String ville = model.getValueAt(index, 4).toString();
        txtVie.setText(ville);
        String adress = model.getValueAt(index, 5).toString();
        txtadress.setText(adress);

        combo.removeAllItems();

        String fouID = model.getValueAt(index, 6).toString();
        String fouName = model.getValueAt(index, 7).toString();
        combo.addItem(fouID + "-" + fouName);
        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();

            String sql = "SELECT * FROM Fournisseurs";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                if (Integer.parseInt(fouID) != rs.getInt(1));
                combo.addItem(rs.getInt("FournisseurID") + "-" + rs.getString("SupplierName"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);


    }//GEN-LAST:event_socTabMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();
        String tele = txtTele.getText();
        String rue = txtRue.getText();
        String ville = txtVie.getText();
        String adress = txtadress.getText();

        String four = (String) combo.getSelectedItem();
        String fournID[] = four.split("-", 0);

        if (validateFields()) {
            JOptionPane.showMessageDialog(null, "all field all requierd");
        } else {
            try {
                Connection con = DatabaseUtil.getConnection();
                // Setting values for the placeholders
                PreparedStatement ps = con.prepareStatement("UPDATE DistributionCompany  set CompanyName=? , CompanyPhone=? ,CompanyStreet=?, CompanyCity=?, CompanyAddress=?,FournisseurID=? where DistributionCompanyID=?");

                // Setting values for the placeholders
                ps.setString(1, name);
                ps.setString(2, tele);
                ps.setString(3, rue);
                ps.setString(4, ville);
                ps.setString(5, adress);

                ps.setString(6, fournID[0]);
                ps.setInt(7, SocietePk);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Societe updated successfully");
                new Societe().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
              DefaultTableModel md = (DefaultTableModel) socTab.getModel();
        md.setRowCount(0);

        try {
            Connection con = DatabaseUtil.getConnection();
            Statement stmt = con.createStatement();
         String sql = "SELECT * FROM DistributionCompany " +
             "INNER JOIN Fournisseurs ON DistributionCompany.FournisseurID = Fournisseurs.FournisseurID " +
             "WHERE CompanyName LIKE '%" + txtSearch.getText() + "%'";


            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
               md.addRow(new Object[]{
                    rs.getInt("DistributionCompanyID"),
                    rs.getString("CompanyName"),
                    rs.getString("CompanyPhone"),
                    rs.getString("CompanyStreet"),
                    rs.getString("CompanyCity"),
                    rs.getString("CompanyAddress"),
                    rs.getInt("FournisseurID"),
                    rs.getString("SupplierName")

                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Societe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Societe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Societe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Societe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Societe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable socTab;
    private javax.swing.JTextField txtRue;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTele;
    private javax.swing.JTextField txtVie;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
